app/models/institution.py
from app.extensions import db


# Institution model
class Institution(db.Model):
    code = db.Column(db.String(255), primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    apikey = db.Column(db.String(255), nullable=False)

    def __repr__(self):
        return '<Institution %r>' % self.code

    # Get the institutions
    @staticmethod
    def get_institutions():
        institutions = db.session.execute(db.select(
            Institution.code,
            Institution.name,
            Institution.apikey
        ).order_by(Institution.name)).mappings().all()
        return institutions

    # Get a single institution
    @staticmethod
    def get_single_institution(code):
        institution = db.session.execute(db.select(Institution).filter(Institution.code == code)).scalar_one_or_none()
        return institution

    # Add the institution to the database
    @staticmethod
    def addinstitution(code, name, apikey):
        institution = Institution(
            code=code,
            name=name,
            apikey=apikey
        )
        db.session.add(institution)  # Add the institution to the database
        db.session.commit()  # Commit the changes

    # Update the institution in the database
    @staticmethod
    def updateinstitution(code, name, apikey):
        institution = Institution.get_single_institution(code)
        institution.name = name
        institution.apikey = apikey
        db.session.commit()  # Commit the changes

app/models/user.py
from app.extensions import db
from datetime import datetime


# User model
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), nullable=False)
    displayname = db.Column(db.String(255), nullable=False)
    emailaddress = db.Column(db.String(255), nullable=True)
    last_login = db.Column(db.DateTime, nullable=True)
    admin = db.Column(db.Boolean, nullable=False, default=False)

    def __repr__(self):
        return '<User %r>' % self.username

    # Log the user into the app
    @staticmethod
    def user_login(session, user_data):
        # Assemble to user's display name
        user_data['DisplayName'] = ''  # Initialize the display name
        if 'GivenName' in user_data:  # if the user has a first name...
            user_data['DisplayName'] += user_data['GivenName'] + ' '  # ...set the first name
        if 'Name' in user_data:
            user_data['DisplayName'] += user_data['Name']

        # Set the session variables
        session['username'] = user_data['UserName']  # Set the username
        session['display_name'] = user_data['DisplayName']  # Set the user's display name
        session['email'] = user_data['Email']  # Set the user's email
        session['authorizations'] = []  # Initialize the user's authorizations

        user = User.check_user(session['username'])  # Check if the user exists in the database

        # If the user is in the database...
        if user is not None:
            User.set_email(user, session)  # ...set the user's email address
            if user.admin:  # ...if the user is an admin...
                session['authorizations'].append('admin')  # ...set the user's authorizations to ['admin']

        # If the user isn't in the database...
        else:
            User.add_user(session)  # ...add the user to the database

    # Check if the user exists in the database
    @staticmethod
    def check_user(username):
        user = db.session.execute(db.select(User).filter(User.username == username)).scalar_one_or_none()
        return user

    # Set the user's email address
    @staticmethod
    def set_email(user, session):
        user.emailaddress = session['email']
        db.session.commit()

    # Set the last login time for the user
    @staticmethod
    def set_last_login(user):
        user.last_login = datetime.now()  # Set the last login time to the current time
        db.session.commit()  # Commit the changes

    # Add the user to the database
    @staticmethod
    def add_user(session):

        # Create the user object
        user = User(
            username=session['username'],
            displayname=session['display_name'],
            emailaddress=session['email'],
            last_login=datetime.now()
        )
        db.session.add(user)  # Add the user to the database
        db.session.commit()  # Commit the changes

    # Get the users
    @staticmethod
    def get_users():
        users = db.session.execute(db.select(
            User.id,
            User.username,
            User.displayname,
            User.emailaddress,
            User.last_login,
            User.admin
        ).order_by(User.username)).mappings().all()
        return users

    # Update the user
    @staticmethod
    def update_user(userid, username, displayname, emailaddress, admin):
        user = db.session.execute(db.select(User).filter(User.id == userid)).scalar_one_or_none()
        user.username = username
        user.displayname = displayname
        user.emailaddress = emailaddress
        user.admin = admin
        db.session.commit()

app/forms/institutionform.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


# Add/Edit Institution Form
class InstitutionForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    code = StringField('Code', validators=[DataRequired()])
    apikey = StringField('API Key', validators=[DataRequired()])

app/forms/uploadform.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import SelectField
from wtforms.validators import DataRequired


# Upload Form
class UploadForm(FlaskForm):
    iz = SelectField('Alma IZ', coerce=str, validators=[DataRequired()])
    csv = FileField('CSV File', validators=[
        FileRequired(),
        FileAllowed(['csv',], 'CSV files only!')
    ])
    almafield = SelectField('Alma Field', choices=[
        'pid',
        'barcode',
        'policy',
        'provenance',
        'description',
        'library',
        'location',
        'pages',
        'pieces',
        'requested',
        'creation_date',
        'modification_date',
        'base_status',
        'awaiting_reshelving',
        'physical_material_type',
        'po_line',
        'is_magnetic',
        'arrival_date',
        'year_of_issue',
        'enumeration_a',
        'enumeration_b',
        'enumeration_c',
        'enumeration_d',
        'enumeration_e',
        'enumeration_f',
        'enumeration_g',
        'enumeration_h',
        'chronology_i',
        'chronology_j',
        'chronology_k',
        'chronology_l',
        'chronology_m',
        'break_indicator',
        'pattern_type',
        'linking_number',
        'type_of_unit',
        'receiving_operator',
        'process_type',
        'inventory_number',
        'inventory_price',
        'alternative_call_number',
        'alternative_call_number_type',
        'storage_location_id',
        'public_note',
        'fulfillment_note',
        'internal_note_1',
        'internal_note_2',
        'internal_note_3',
        'statistics_note_1',
        'statistics_note_2',
        'statistics_note_3',
        'physical_condition',
        'committed_to_retain',
        'retention_reason',
        'retention_note'
    ], default='internal_note_1', validators=[DataRequired()])

app/forms/userform.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField
from wtforms.validators import DataRequired


# Add/Edit User Form
class UserForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    displayname = StringField('Display Name', validators=[DataRequired()])
    emailaddress = StringField('Email', validators=[DataRequired()])
    admin = BooleanField('Admin')

app/upload/__init__.py
from flask import Blueprint

bp = Blueprint('upload', __name__)

from app.upload import routes

app/upload/routes.py
from flask import render_template, flash, redirect, url_for, session, current_app, request, abort
from pymemcache.client.base import Client as memcacheClient
import app.forms.uploadform as uploadform
import app.forms.institutionform as institutionform
import app.forms.userform as userform
from functools import wraps
from werkzeug.utils import secure_filename
from app.tasks.batch import batch
from celery.result import AsyncResult
import os
from app.models.user import User
from app.models.institution import Institution
from app.models.batchimport import BatchImport
from app.upload import bp
from dotenv import load_dotenv

load_dotenv()


# decorator for pages that need auth
def auth_required(f):
    @wraps(f)  # preserve the original function's metadata
    def decorated(*args, **kwargs):  # the wrapper function
        if 'username' not in session:  # if the user is not logged in
            return redirect(url_for('upload.login'))  # redirect to the login page
        else:
            return f(*args, **kwargs)  # otherwise, call the original function

    return decorated


@bp.route('/', methods=['GET', 'POST'])
@auth_required
def upload():
    form = uploadform.UploadForm()  # Initialize the upload form
    izs = Institution.get_institutions()  # Get the institutions from the database
    form.iz.choices = [(i.code, i.name) for i in izs]  # Set the choices for the institution field
    form.iz.default = 'scf'  # Set the default institution to 'scf
    if form.validate_on_submit():
        # File
        file = form.csv.data  # Get the CSV file from the form
        filename = secure_filename(file.filename)  # Get the filename from the file

        # If the filename already exists in the upload folder...
        if os.path.exists(os.path.join(current_app.config['UPLOAD_FOLDER'], filename)):
            name, ext = os.path.splitext(file.filename)  # ...get the filename and extension
            count = 0  # ...initialize filecount
            # ...while the filename and filecount exists...
            while os.path.exists(os.path.join(current_app.config['UPLOAD_FOLDER'], name) + '-{}'.format(count) + ext):
                count += 1  # ...increment the filecount until the filename doesn't exist
            filename = name + '-{}'.format(count) + ext  # ...add the new filecount to the filename

        secfilename = secure_filename(filename)  # Make the filename safe, even though it should be safe already

        # Save the file to the CSV folder in the instance path
        file.save(os.path.join(
            current_app.config['UPLOAD_FOLDER'], secfilename
        ))

        # Field
        field = form.almafield.data  # Get the Alma field from the form

        iz = form.iz.data  # Get the institution from the form
        apikey = Institution.get_single_institution(iz).apikey  # Get the API key for the institution

        user = User.check_user(session['username'])  # Get the current user object

        # Run the batch function on the CSV file
        task = batch.delay(
            os.path.join(
                current_app.config['UPLOAD_FOLDER'], secfilename
            ), field, user.emailaddress, apikey
        )

        # Add task to database
        BatchImport.add_batch_import(task.id, filename, field, user.id, iz)

        # Provide import info as message to user
        flash(
            'The CSV "' + filename + '" is being processed (taskid = ' + str(
                task.id) + '). An email will be sent to {} when complete.'.format(session['email']),
            'info'
        )
        return redirect(url_for('upload.upload'))

    # Get batch imports from database
    batch_imports = BatchImport.get_batch_imports()  # Get the batch imports from the database
    imports = []  # Initialize the imports list
    for batch_import in batch_imports:  # Iterate through the batch imports
        result = AsyncResult(batch_import.uuid).result  # Get the result of the task
        imports.append({  # Add the batch import to the imports list with the status and result
            'filename': batch_import.filename,
            'field': batch_import.field,
            'date': batch_import.date,
            'user': batch_import.displayname,
            'institution': batch_import.name,
            'result': result
        })
    return render_template('upload.html', form=form, imports=imports, uploadfolder=current_app.config['UPLOAD_FOLDER'])


@bp.route('/login')
def login():
    if 'username' in session:
        return redirect(url_for('upload.upload'))
    else:
        login_url = current_app.config['SAML_SP']
        login_url += current_app.config['COOKIE_ISSUING_FILE']
        login_url += '?institution='
        login_url += current_app.config['INSTITUTION_CODE']
        login_url += '&service='
        login_url += current_app.config['SERVICE_SLUG']
        return render_template('login.html', login_url=login_url)


@bp.route('/login/n')
def new_login():
    session.clear()
    cookie_name = current_app.config['COOKIE_PREFIX'] + current_app.config['SERVICE_SLUG']
    memcached_server = current_app.config['MEMCACHED_SERVER']
    if cookie_name in request.cookies:
        memcached_key = request.cookies[cookie_name]
        memcached = memcacheClient((memcached_server, 11211))
        user_data = {}
        for line in memcached.get(memcached_key).decode('utf-8').splitlines():
            key, value = line.split('=')
            user_data[key] = value
        User.user_login(session, user_data)  # Log the user in
        return redirect(url_for('upload.upload'))  # Redirect to the upload page
    else:
        return "no login cookie"  # if the login cookie is not present, return an error


# Logout handler
@bp.route('/logout')
@auth_required
def logout():
    session.clear()  # clear the session
    return redirect(  # redirect to the logout script
        current_app.config['SAML_SP'] +
        current_app.config['LOGOUT_SCRIPT'] +
        '?service=' +
        current_app.config['SERVICE_SLUG'])


# Institutions handler
@bp.route('/institutions')
@auth_required
def institutions():
    if 'admin' not in session['authorizations']:
        abort(403)
    izs = Institution.get_institutions()
    return render_template('institutions.html', izs=izs)


# Institution handler
@bp.route('/institutions/<code>', methods=['GET', 'POST'])
@auth_required
def edit_institution(code):
    if 'admin' not in session['authorizations']:
        abort(403)
    iz = Institution.query.get_or_404(code)
    form = institutionform.InstitutionForm(obj=iz)
    if form.validate_on_submit():
        Institution.updateinstitution(form.code.data, form.name.data, form.apikey.data)
        flash(form.name.data + ' updated', 'info')
        return redirect(url_for('upload.institutions'))
    return render_template('edit_institution.html', form=form)


# Add institution handler
@bp.route('/institutions/add', methods=['GET', 'POST'])
@auth_required
def add_institution():
    if 'admin' not in session['authorizations']:
        abort(403)
    form = institutionform.InstitutionForm()
    if form.validate_on_submit():
        Institution.addinstitution(form.code.data, form.name.data, form.apikey.data)
        flash('Institution added', 'info')
        return redirect(url_for('upload.institutions'))
    return render_template('add_institution.html', form=form)


# Users handler
@bp.route('/users')
@auth_required
def users():
    if 'admin' not in session['authorizations']:
        abort(403)
    allusers = User.get_users()
    return render_template('users.html', allusers=allusers)


# Edit User handler
@bp.route('/users/<userid>', methods=['GET', 'POST'])
@auth_required
def edit_user(userid):
    if 'admin' not in session['authorizations']:
        abort(403)
    edituser = User.query.get_or_404(userid)
    form = userform.UserForm(obj=edituser)
    if form.validate_on_submit():
        User.updateuser(edituser.id, form.username.data, form.displayname.data, form.emailaddress.data,
                        form.admin.data)
        flash(edituser.displayname + ' updated', 'info')
        return redirect(url_for('upload.users'))
    return render_template('edit_user.html', form=form)


# set up error handlers & templates for HTTP codes used in abort()
#   see http://flask.pocoo.org/docs/1.0/patterns/errorpages/
# 400 error handler
@bp.errorhandler(400)
def badrequest(e):
    return render_template('error_400.html', e=e), 400  # render the error template


# 403 error handler
@bp.errorhandler(403)
def forbidden(e):
    return render_template('unauthorized.html', e=e), 403  # render the error template


# 500 error handler
@bp.errorhandler(500)
def internalerror(e):
    return render_template('error_500.html', e=e), 500  # render the error template

app/templates/add_institution.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add Institution</h1>
    <form method="POST"  enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="mb-3 required">
            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control") }}
        </div>
        <div class="mb-3 required">
            {{ form.code.label(class="form-label") }}
            {{ form.code(class="form-control") }}
        </div>
        <div class="mb-3 required">
            {{ form.apikey.label(class="form-label") }}
            {{ form.apikey(class="form-control") }}
        </div>
        <div class="actions">
            <input type="submit" value="Add Institution"  class="btn btn-primary" />
        </div>
    </form>
{% endblock %}
```

app/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}WRLC Alma Notes Import{% endblock %} </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
        <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    </head>
    <body>
        <header class="header mb-4">
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                <div class="container">
                    <div class="collapse navbar-collapse" id="navbarText">
                        <ul class="navbar-nav mr-auto">
                            <li class="navbar-header">
                                <a class="navbar-brand" href="{{ url_for('upload.upload') }}">
                                    <img class="logo" src="{{ url_for('static', filename='images/wrlc-logo-7-white.png') }}" alt="WRLC logo" /> WRLC Alma Notes Import
                                </a>
                            </li>
                            {% if 'username' in session %}
                                {% if 'admin' in session['authorizations'] %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ url_for('upload.institutions') }}">Institutions</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ url_for('upload.users') }}">Users</a>
                                    </li>
                                {% endif %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('upload.logout') }}">Logout</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <div class="messages">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-info" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
            {% block content %} {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    </body>
</html>

app/templates/edit_institution.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ form.name.data }} - Edit Institution</h1>
    <form method="post">
    {{ form.csrf_token }}
        <div class="mb-3 required">
            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control") }}
        </div>
        <div class="mb-3 required">
            {{ form.code.label(class="form-label") }}
            {{ form.code(class="form-control", disabled=True, ariadescribedby="codeHelpBlock") }}
            <div id="codeHelpBlock" class="form-text">The institution code cannot be changed.</div>
        </div>
        <div class="mb-3 required">
            {{ form.apikey.label(class="form-label") }}
            {{ form.apikey(class="form-control") }}
        </div>
        <div class="actions">
            <input type="submit" value="Update Institution"  class="btn btn-primary" />
            <a class="btn btn-secondary" href="{{ url_for('upload.institutions') }}">Cancel</a>
        </div>
    </form>
{% endblock %}

app/templates/edit_user.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ form.username.data }} - Edit</h1>
    <form method="post">
        {{ form.csrf_token }}
        <div class="mb-3">
            {{ form.username.label(class="form-label") }}
            {{ form.username(class="form-control", disabled=True) }}
        </div>
        <div class="mb-3">
            {{ form.displayname.label(class="form-label") }}
            {{ form.displayname(class="form-control", disabled=True) }}
        </div>
        <div class="mb-3">
            {{ form.emailaddress.label(class="form-label") }}
            {{ form.emailaddress(class="form-control", disabled=True) }}
        </div>
        <div class="mb-3">
            {{ form.admin.label(class="form-label") }}
            {{ form.admin }}
        </div>
        <input type="submit" value="Update User"  class="btn btn-primary" />
            <a class="btn btn-secondary" href="{{ url_for('upload.users') }}">Cancel</a>
    </form>
{% endblock %}

app/templates/error_400.html
{% extends 'base.html' %}

{% block content %}
	<h5>400 Bad Request</h5>
	<p>The Alma API reported a bad request that could not be understood by the server. Please note the date and time, and exactly what you were doing, and report it to <a href="mailto:servicedesk@wrlc.org?subject=Fine+Fee+App+400+Error">ServiceDesk@wrlc.org</a></p>
{% endblock %}

app/templates/error_500.html
{% extends 'base.html' %}

{% block content %}
	<h5>Internal Server Error</h5>
	<p>The server encountered an internal error and was unable to complete your request. Please note the date and time, and exactly what you were doing, and report it to <a href="mailto:servicedesk@wrlc.org?subject=Fine+Fee+App+500+Error">ServiceDesk@wrlc.org</a></p>
{% endblock %}

app/templates/institutions.html
{% extends 'base.html' %}

{% block content %}
    <div class="d-flex justify-content-between align-items-center">
        <h1>Institutions</h1>
        <div>
            <a href="{{ url_for('upload.add_institution') }}" class="link-light link-underline-opacity-0 btn btn-primary">Add Institution</a>
        </div>
    </div>
    <table class="table table-bordered table-hover table-sm">
        <thead class="table-dark sticky-top">
            <tr>
                <th>Name</th>
                <th>Code</th>
                <th>API Key</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>
            {% for iz in izs %}
                <tr>
                    <td>{{ iz.name }}</td>
                    <td>{{ iz.code }}</td>
                    <td class="text-danger">{{ iz.apikey }}</td>
                    <td><a href="{{ url_for('upload.edit_institution', code=iz.code) }}">Edit</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
```

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Login</h1>
    <p><a href="{{ login_url }}">Click here to log in with your WRLC ID</a></p>
{% endblock %}

app/templates/unauthorized.html
{% extends 'base.html' %}

{% block content %}
	<h5>Error 403 Forbidden</h5>
	<p>You don't have permission to access the requested resource. You may not have an account in Alma or your account does not have the necessary role assigned.</p>
{% endblock %}

app/templates/upload.html
{% extends 'base.html' %}

{% block content %}
    {% set path = uploadfolder|replace('app/', '') %}
    <h1 class="mb-3">Batch update Alma field by barcode</h1>
    <div class="text-muted mb-2">
        <small>Alma has defined a list of valid values for some fields. This app does <strong>NOT</strong> check whether the values in your CSV match these defined values before attempting to update them in Alma.</small>
    </div>
    <div class="text-muted mb-3">
        <small>If a value isn't valid, it will result in a <strong>400 Bad Request</strong> error for that barcode.</small>
    </div>
    <form method="POST"  enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="mb-3 required">
            {{ form.iz.label(class_='form-label') }}<br />{{ form.iz(class_='form-control') }}
        </div>
        <div class="mb-3 required">
            {{ form.csv.label(class_='form-label') }}<br />{{ form.csv(class_='form-control') }}
            <div class="text-muted"><small class="text-muted">CSV should not contain a header row and should have only two columns: <strong>Barcode</strong> and <strong>Field Value.</strong></small></div>
        </div>
        {% if form.csv.errors %}
            {% for error in form.csv.errors %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>
            {% endfor %}
        {% endif %}
        <div class="mb-4 required">
            {{ form.almafield.label(class_='form-label') }}<br />{{ form.almafield(class_='form-control') }}
            <div class="text-muted">
                <small class="text-muted">When selecting the following fields, values in the CSV's second column should include a <strong>Value</strong> and <strong>Description</strong> separated by a pipe ('|'):</small>
                    <ul>
                        <li><small>policy</small></li>
                        <li><small>library</small></li>
                        <li><small>location</small></li>
                        <li><small>base_status</small></li>
                        <li><small>physical_material_type</small></li>
                    </ul>
            </div>
        </div>
        <div class="actions">
            <input class="btn btn-primary mb-4" type="submit" value="Batch Update">
        </div>
    </form>
    {% if imports|length > 0 %}
        <h2 class="mb-3">Import History</h2>
        <table class="table table-bordered table-hover table-sm report">
            <thead class="table-dark sticky-top">
                <tr>
                    <th>Uploaded</th>
                    <th>By</th>
                    <th>IZ</th>
                    <th>CSV</th>
                    <th>Field</th>
                    <th>Result</th>
                </tr>
            </thead>
            {% for import in imports %}
                <tr>
                    <td>{{ import.date }}</td>
                    <td>{{ import.user }}</td>
                    <td>{{ import.institution }}</td>
                    <td><a href="/{{ path }}/{{ import.filename }}">{{ import.filename }}</a></td>
                    <td>{{ import.field }}</td>
                    <td><pre>{{ import.result }}</pre></td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}

app/templates/users.html
{% extends 'base.html' %}

{% block content %}
    <h1>Users</h1>
    {% if allusers|length == 0 %} }}
        <p>No users found.</p>
    {% else %}
        <table class="table table-bordered table-hover table-sm">
            <thead class="table-dark sticky-top">
                <tr>
                    <th>Username</th>
                    <th>Display Name</th>
                    <th>Email</th>
                    <th>Admin?</th>
                    <th>Last Login</th>
                    <th>Edit</th>
                </tr>
            </thead>
            <tbody>
                {% for user in allusers %}
                    <tr>
                        <td>{{ user.username }}</td>
                        <td>{{ user.displayname }}</td>
                        <td>{{ user.emailaddress }}</td>
                        <td>{{ user.admin }}</td>
                        <td>{{ user.last_login }}</td>
                        <td><a href="{{ url_for('upload.edit_user', userid=user.id) }}">Edit</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}